kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-prod-data
  namespace: wiki
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wiki-azure-standard
  volumeMode: Filesystem