apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wiki-azure-standard
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
  location: eastasia
